//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgAvanzada_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
        public int IdTipoUsuario { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }

        public static bool Login(string User, string pass)
        {
            bool b = false;
            try
            {
                using (var entities = new MagnaEnciclopediaAnimalTurboEntities())
                {
                    b = entities.Usuario.Any(x => x.Usuario1 == User && x.Contraseña == pass);
                }
            }

            catch (Exception e)
            {
                throw e;
            }
            return b;
        }
    }
}
